{% set name = "traces" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/datascopeanalytics/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dadac5bebf5d48d099ec8d301864a7cc9d763226ea3ae8a68fd6ec16998737ed

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - arrow
    - future
    - intervals
    - sortedcontainers <=2

test:
  imports:
    - traces

about:
  home: https://github.com/datascopeanalytics/traces
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python library for unevenly-spaced time series analysis'
  description: |
    A Python library for unevenly-spaced time series analysis.
  doc_url: https://traces.readthedocs.io/en/master/index.html
  dev_url: https://github.com/datascopeanalytics/traces

extra:
  recipe-maintainers:
    - mvdbeek
