{% set name = "traces" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/datascopeanalytics/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 843c6c36313c71ff0d0519a47cf9ddb4f059e0d3dd8ab24425f3f7df71f7203e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - arrow
    - future
    - intervals
    - sortedcontainers <=2

test:
  requires:
    - python {{ python_min }}
  imports:
    - traces

about:
  home: https://github.com/datascopeanalytics/traces
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python library for unevenly-spaced time series analysis'
  description: |
    A Python library for unevenly-spaced time series analysis.
  doc_url: https://traces.readthedocs.io/en/master/index.html
  dev_url: https://github.com/datascopeanalytics/traces

extra:
  recipe-maintainers:
    - mvdbeek
