{% set name = "traces" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/datascopeanalytics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0ad4f6f6267a4a2b96488b987663bae758be401c47273846e6bff11def4af0be

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - arrow
    - future
    - intervals
    - sortedcontainers <=2

test:
  imports:
    - traces

about:
  home: https://github.com/datascopeanalytics/traces
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python library for unevenly-spaced time series analysis'
  description: |
    A Python library for unevenly-spaced time series analysis.
  doc_url: https://traces.readthedocs.io/en/master/index.html
  dev_url: https://github.com/datascopeanalytics/traces

extra:
  recipe-maintainers:
    - mvdbeek
