travis:
  secure:
    BINSTAR_TOKEN: MJeiplzlRoRlA3jy4AcuYKjC4DmN5RKDC9UIXM1jSlyMjhOdusmi6XaqxvYSJKvkpkrvs86j5c/KuMVMMYP+BrG+rOlqr8Fr1muwTc1JpUtY6svD9sYD41pRiIf7z1NEYzHudGvOtMQuBnPVZbY02nCA7F4pG1FJs5jby6ek3MhLFVIUf2mDe4JwvdrOAr3TL92aSIyqA7/+JvUioJVBaXKowrnMWWxiUizpXSpnxZWqt1burkp4zSd+JmeeExLK5OYQYxbnri710aJcnSEBjWqFmZOmV9uZnCC4bsJ28/VrGIEEqjRySx2N7mX/asZaFYzfJqznbVqlqZXh6BmlNuFYTPwhEeItfnMW5UGiusFROprGKf90RkaDtkBzB8VNT3POeCk/v3X+r5t94MZr3YK50eQKdXTtdU5bdmW8IBDSPQrQ5ENzp/mMDcaootvjfTDUan2ZWVvlzXRRHIABpyD4ft0/9TN9WcWQSLTPQ1Ecnw6Alx5UMs54QxixFxQ7I8tM9PuqUfc3R0Wzb37rzN6J5pwi1zLGuuL98KIWVc+Gxen/OzvmtH3Kvnk9lqa4g7MrQxR+z/lv+9QasqEPUxn3N9+0+d9uSqPQ9msqGhavwY5Yr2zg8Z/ZxBg4CVePuCl7Vxw6H0gAl57C5SqIIk5Bcl+BMKAxAvF14hdaLro=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
