travis:
  secure:
    BINSTAR_TOKEN: LLggh77PQ7U6zTP3lzc3mBIRndajGnyoJnUlp7PTsmNl28RU7akaVA11ozAXYso3Ec24PhWrhWYCcRebFPhyqMrfK/PbbiUmvAEtVWivJR6c5qbSMsPfK6/zjTNxW96msNNFVpef3uQ76GdpsAvxMH7Dao51paQ6qlyfnlCvukT3CSjAvNkZyzukKkyHfuec3Y2e4CWYzPks6kBsTAMOD+8dMtiYOs6Zgw/VFlweLHiTDWD5fuZq4t/nhZ0zZMJZ8YFbtiC1nDPmz5UBaISxQnoWWXDyHjlHLqT0P49UxiQ7Dvu5cZlg51WC/bpSYQ3LsJithHPrIq09ciA447gC6LY9j80RCqccMi182g+pAN5z1UHHmB6fudWPepZBOtb5/rEl6ivx6Py7SeP71Q1uKtNqp9LDjbSNY0FjjVTkvUY/OvaulSEO7JIPQmvAuR5CZaUOKMSpTo78CYuDQSlUwXbtK+EBTB6W/TtKAH1iWrUGrs6Y1Hyj4LU49gWfBDh1eNs7cZssInQMmYECBxF011ifUD2LSmlJuK3w2pfGILkHpIyhepsBFfkXL7g0TUuS6q3MgTC+rfcTUwrco9gpbzdL07yEgJYcsKxUrtCWX32Nk3zqhfaqdTa6iICGFfzSILozvJjxnd8jiA7aF6owGeJIKRVvNMTp2RbGGmOoD2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
